### ISSUE TITLE
Suggestion/Idea: Zombie Edition upgrades as NPCs

### ISSUE THREAD

**Issue by Busybody64** [VJ-HLR-Developers/Half-Life-Zombie-Edition-SNPCs#6]
Basically, these are variants of the HL1 Headcrab Zombie, except they each have the abilities from the 3 upgrade paths in the Zombie Edition mod. They also have smarter AI than you'd expect from a Headcrab Zombie.

Runner: Looks like a Scientist Zombie, except parts of its limbs, most notably the bottom part of its legs, are missing so much flesh and stuff that you can see its skeleton. (It's the only part of its limbs that hasn't rotten off of its body entirely.) It actually DOESN'T try to rush towards you like a Fast Zombie. Instead, it tries to hide in the darkness and sneak up on it's victims, before surprise-attacking them by long jumping at them and hitting them with a stronger than normal blow. (It's not instant death, it just hurts more than usual.) It DOES run when idle, or when it's chasing somebody that already saw and/or tried to kill it. In the latter case, it'll even use the long jump ability to try and catch up with it's target. It's footsteps are also silent unless it's running. In case it doesn't sound strong enough already, it also attacks WAY faster than normal Zombies do, although it's still not as fast as the Gonome's attacks are. 

Breeder: Looks like a Guard Zombie, except with severed Barnacle tongues wrapped around it's body. It has 3 normal Headcrabs on it, which it will throw at it's targets like a Poison Zombie throwing it's Poison Headcrabs. If there are any normal headcrabs nearby, it'll pick them up, so it can throw them at somebody later on. It'll also throw... *something* at you if you're too far away or it ran out of Headcrabs to throw, sorta like the Gonome does. New to Resurgence, to try and make it more unique than normal zombies, it actually holds part of a Barnacle Tongue in it's hand, and uses it like a whip to increase it's melee attack range! It can also walk underneath a Barnacle with getting grabbed by it's tongue.

Crasher: Looks like a HECU Zombie, except with what appears to be broken parts of machinery covering it's body, mostly on it's hands. It's slower than normal, due to how heavy the machine parts covering it's body are, but it hits like a TRUCK. It's able to attack props around the size of a soda machine, which will basically fling them like a HL2 zombie, except with less force and knockback from the hit, and will also attack closed doors hard enough to force them open. (Unless it's locked, obviously.) Even worse; it'll attack breakable objects that're in the way of it's path, (And it's target.) and it won't stop until said objects are destroyed, and it's able to continue it's path. (So things like wooden boards, wooden crates, and comically large vent covers.)

Other/Shared AI Quirks: 
- All 3 Upgraded Zombies actually DO react to grenades. The Rusher just runs away, the Breeder smacks it with it's Barnacle Whip, likely pushing it too far away for the explosion to kill it, and the Crasher throws it BACK to whoever threw the grenade.
- The Rusher and Breeder both try to run away from Bullsquids, (Although the breeder DOES throw it's... *projectile* after getting far enough from the Bullsquid.) while the Crasher will instantly stop attacking whatever it's already trying to kill, and will instead rush towards the Bullsquid that it saw to try and maul it to death. (It'll keep going until their corpse is completely GIBBED!)

**Comment by Cpt-Hazama** [comment]
Unless you can magically create models/animations for these, we won't add them

**Comment by epicplayer40** [comment]
This will not be added. The goal of this addon is to remake the NPCs seen in the Zombie Edition mod rather than create new NPCs that are just inspired from it.
